project:
  type: website

website:
  title: "GeoJupyter Workshop: CSDMS Annual Meeting 2025"
  navbar:
    left:

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
