project:
  type: "website"

website:
  title: "GeoJupyter Workshop: CSDMS 2025"
  site-url: "https://geojupyter.github.io/workshop-csdms2025/"

  repo-url: &repo-url "https://github.com/geojupyter/workshop-csdms2025"
  repo-actions: ["edit", "issue"]

  navbar:
    left:
      - text: "1 - Collaborating in JupyterHub"
        href: "01-collaborating-in-jupyterhub.md"
      - text: "2 - New geospatial tools"
        href: "02-new-geospatial-tools.md"
      - text: "3 - Sharing your work"
        href: "03-sharing-your-work.md"

    right:
      - icon: "github"
        aria-label: "GitHub"
        href: "https://github.com/geojupyter"

format:
  html:
    from: "markdown+emoji"
    theme:
      - "cosmo"
      - "brand"
    css: "styles.css"
    toc: true
