project:
  type: "website"

website:
  title: "GeoJupyter Workshop: CSDMS 2025"
  navbar:
    left:
      - text: "1 - Collaborating in JupyterHub"
      - text: "2 - New geospatial tools"
      - text: "3 - Sharing your work"

format:
  html:
    from: "markdown+emoji"
    theme:
      - "cosmo"
      - "brand"
    css: "styles.css"
    toc: true
