[workspace]
authors = ["Matt Fisher <mfisher87@gmail.com>"]
channels = ["conda-forge"]
name = "workshop-csdms2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
render = "quarto render"
preview = "quarto preview"

[dependencies]
quarto = ">=1.6.43,<2"
